### ISSUE TITLE
[question] What does BASIC stand here for? I mean which dialect/standard?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#178]
What does BASIC stand here for?
Is it Tiny BASIC? Or some specific dialect? Microsoft BASIC? Which one?
Is there a manual about the BASIC language compiled by ACK?

**Comment by drawkula** [comment]
https://github.com/davidgiven/ack/blob/default/doc/basic.doc has some answers.

**Comment by Fabrizio-Caruso** [comment]
@drawkula  Thanks!
What do I need to see the .doc file correctly? I see lots of formatting characters.

**Comment by drawkula** [comment]
`groff -ms basic.doc -Tpdf >/tmp/basic.pdf` worked for me on Debian9. It took a while to find out that having only `groff-base` installed is not enough because the `ms.tmac` macros were missing. After installing the package `groff` the above command worked as expected.

—▷ [basic.pdf](https://github.com/davidgiven/ack/files/2948682/basic.pdf)

**Comment by davidgiven** [comment]
There's formatted copies in both PDF and HTML here.
http://tack.sourceforge.net/olddocs.html

It's a fairly simple subset of Microsoft Basic. There is actually a Basic
language standard:

https://www.ecma-international.org/publications/files/ECMA-ST-WITHDRAWN/ECMA-55,%201st%20Edition,%20January%201978.pdf

...but the ACK Basic manual doesn't mention it and it's probably not
compliant.
