### ISSUE TITLE
em_led can't handle addresses >= 0x80010000

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#4]
I seem to have met a bug in em_led (util/led) while trying to get plat/linuxppc to work. With my local changes, I am building linuxppc executables that sometimes crash. One such executable (a modified examples/paranoia.c) had a string at 0x800120cc, but the machine code tries to load it from 0x800020cc. I had compiled it this way:

```
$ ack -mlinuxppc -o modpar.linuxppc modpar.c
$ ack -mlinuxppc -c.out modpar.c
$ ack -mlinuxppc -c.s modpar.c
```

By studying modpar.s, I found my string at label _544. By running `anm modpar.out`, I found the address: `800120cc  1  - _544`. By running `gdb modpar.linuxppc` on the target machine (Debian 8.5 in qemu-system-ppc), gdb disassembled this code:

```
   0x80003d20:  3d 80 80 00     lis     r12,-32768
   0x80003d24:  61 8c 20 cc     ori     r12,r12,8396
   0x80003d28:  95 81 ff fc     stwu    r12,-4(r1)
=> 0x80003d2c:  48 00 06 85     bl      0x800043b0
```

As I had stopped the program there (with `break *0x80003d2c`), gdb showed me that $r12 contained 0x800020cc, but I wanted the string at 0x800120cc:

```
(gdb) print/x $r12
$1 = 0x800020cc
(gdb) print/s (char*)0x800020cc
$2 = 0x800020cc "H"
(gdb) print/s (char*)0x800120cc
$3 = 0x800120cc "Trying to enter the main loop.\n"
```

This seems to be a bug in em_led: it put the correct address 0x800120cc in the symbol table (as I saw in anm) but the wrong address 0x800020cc in the relocated machine code.

I might not fix this bug. I will try to dodge this bug by loading code at a lower address. plat/powerpc/descr was using `-b0:0x80000054` but linux386 and linux68k are already using lower addresses. One might reproduce this bug by using `-b0:0x80000054` and putting printf("Some string\n") in paranoia's main(). Strings in 0x8000???? work but strings in 0x8001???? fail, so the problem seems to start around 0x80010000.

**Comment by davidgiven** [comment]
> I seem to have met a bug in em_led (util/led) while trying to get plat/linuxppc to work. 

...and may any gods you desire have mercy on your soul...

Okay, so, I wrote the PowerPC code generator, and it's terrible; ncg can't cope with that many registers. I got it working, more or less, but then I tried to add floating point support and it died (what happens is that ncg only uses the register size to distinguish registers; so it would either store floating point values in integer registers and copy them into floating point registers to do work before copying them back, or else it would store _integer_ values in floating point registers and copy them back to do work...). And the code was embarrassingly bad.

Okay, so, I think I know what's going on here.

The PowerPC a.out format doesn't have a special relocation for lis/ori pairs, instead emitting a RELOH2 relocation for the high word and a RELO2 relocation for the low word. See the e16 rule in mach/powerpc/as/mach4.c for where that's generated. The relocations are resolved in util/led/relocate.c,  in the getvalu() and putvalu() functions; getvalu() reads an offset out of the machine code, which is then added to the symbol address, and putvalu() patches it back into the machine code.

I bet what's happening here is that it's not handling overflows. Because there are two separate relocations with two different offsets, then the case where adding the offset to the low part of the address overflows and requires the high part to be adjusted simply isn't happening.

I think I've managed to duplicate this --- I can certainly see such a bogus relocation...

My suspicion is that the two-part relocations as used here are simply not going to work, and it's going to need a proper lis/ori relocation. That'll need:
- modifying the code generator to generate a `la r4, symbol` pseudoinstruction instead of a lis/ori pair;
- modifying the assembler to recognise these, and expand them into the lis/ori pair with a proper RELOPPC relocation;
- modifying led so that when it sees a RELOPPC relocation it looks at the opcode to figure out what it is and does the right thing (same principle as the existing RELOVC4).

The actual amount of works pretty trivial, but I need to go to bed so I'm not going to do it right now. Sorry! I'll have a look later (unless you want to give it a try?).

BTW, I brought the dtrg-experimental-powerpc branch mostly up to date. It doesn't build completely because the modula-2 programs need some missing helper functions, but you might find it useful.

**Comment by davidgiven** [comment]
I've hacked in a fix (in the dtrg-experimental-powerpc branch).

Paranoia still doesn't run, but it crashes in a different place now, much later on.

**Comment by kernigh** [comment]
Thanks for the linker fix. I had already coded the missing .lar4 and .sar4 helpers for modula-2, but was not able to test them without the linker fix.

I will be pushing commits to
https://github.com/kernigh/ack/tree/kernigh-linuxppc

As of e4ce7da, Hi/Lo for C, Modula-2, Pascal are working, Paranoia seems to work, Star Trek has at least a display glitch, and Hilo Basic fails. My goal is to add an osxppc platform for my PowerPC Mac running OS X 10.4.11.
