### ISSUE TITLE
undefined behavior in cpp.ansi/LLlex.c

### ISSUE THREAD

**Issue by hexcoder-** [davidgiven/ack#56]
cppcheck reports
lang/cem/cpp.ansi/LLlex.c:265

shifting a 32-bit value (1) by 63 bits (from sizeof(long)) is undefined behavior
and gives  a signed integer overflow.
Patch:
		arith ubound = ~(1<<(sizeof(arith)*8-1))/(base/2);
=>
		arith ubound = ~(1UL<<(sizeof(arith)*8-1))/(base/2);

Probably this was no problem as long as sizeof(int) == sizeof(long)...

**Comment by kernigh** [comment]
Thanks for finding this. The code was always wrong, because in the past, some machines had sizeof(int) == 2 && sizeof(long) == 4.

lang/cem/cemcom.ansi/arith.h has
```c
./arith.h:#define       arith_sign      ((arith) 1 << (arith_size * 8 - 1))
```

That's better, but still causes signed overflow, because it overflows a positive 1 in trying to set a negative sign bit. I understand that signed overflow is undefined behavior in modern C.

Your 1UL would fix it, as long as arith is long. If someone changed arith to be wider than long, then 1UL<<... would cause undefined behavior, because the shift would be too large.

I wonder if (arith)-1<<... would work.

**Comment by davidgiven** [comment]
Obsolete.
