### ISSUE TITLE
Does not build on case insensitive filesystems

### ISSUE THREAD

**Issue by davidgiven** [davidgiven/ack#58]
...such as Windows through Cygwin.

There are problems where files like scope.C are preprocessed and scope.c produced. Sample log attached.

[ack-log-Cygwin-20170723.txt](https://github.com/davidgiven/ack/files/1184422/ack-log-Cygwin-20170723.txt)

**Comment by trijezdci** [comment]
Ideally compilers/preprocessors should never overwrite any existing file.

In our Modula-2 preprocessor, if the parameters are such that an existing file is to be replaced by the preprocessor, I rename the file to be replaced to a backup name, for example, Foobar.mod would be renamed to Foobar.mod.BAK, and if there is already such a file, then Foobar.mod.BAK;1, again if there is already such a file, then Foobar.mod.BAK;2 etc etc. There is also a means to set the upper limit for the version number. If the limit is reached the preprocessor emits an error to the user who will need to purge the backup files then.

https://github.com/m2sf/m2pp/blob/master/src/FNStr.def#L40

This way, the preprocessor never needs to delete nor overwrite any files.

Using this strategy, an input file scope.C would be renamed to scope.C.BAK and the preprocessor would create a new file scope.c which would not cause a problem in a case insensitive file system.

The code is in Modula-2, but could be easily transcribed to C. The license is LGPL2.1. Feel free to use it if you like.

You may also find the filename translation layer of our Modula-2 compiler of interest. In Modula-2 filenames should match the module identifiers for a compiler to find the module's definition and implementation files. However, this can be problematic on case insensitive file systems and even more so on older platforms where filenames are severely restricted in length such as MS-DOS and the PDP's RT-11/RSX-11 operating systems.

In each directory where the compiler looks for sources, it checks if there is a plain text file of a hardcoded short filename that contains key/value pairs of filename translations.

If such a translation file is found, it reads the file and translates filename accordingly before trying to read source files and it uses the same translated basename for output files such as symbol and object files.

https://github.com/m2sf/m2bsk/blob/master/src/FilenameXlat.def#L9

This way one could move projects with long filenames to file systems with length restricted filenames and still compile them without modifying the sources to adjust for the shorter filenames.

This might be a worthwhile addition to ACK since it supports a number of older platforms that had length restricted filenames. Note I have not yet done the implementation of this module, it is on my to do list for this month though.

I will also backport both facilities to M2C, which is written in C, so eventually I will have C transcriptions of those libraries.

**Comment by davidgiven** [comment]
I'm unwilling to use filename translation because there are always edge cases where some programs use translation and some don't --- I've dealt with these before.  We can't use translation everywhere because of the need to use external tools. The problems are particularly bad if the translated filename isn't attached to the actual file. For example, someone renames the file in git but doesn't check in the updated translation table.

I'm not well up on Modula2. I assume that the reason for this requirement is to allow the compiler to find the appropriate `.def` file when importing symbols? The `.mod` files have to be specified explicitly when compiling a program, so the filenames are irrelevant there. Possibly it would suffice to just tell the compiler which modules live in which `.def` files at application build time would do; that way there's just one thing to change.

Also, regarding versioning: the specific problem here isn't that the file in the source tree is being redefined --- it's that we have a scope.C in the source, and the preprocessed scope.c in the build tree (which is never modified by the build process), but they're both on the path and the compiler is trying to read scope.c but finding scope.C instead. The scheme wouldn't help here because nothing is being overwritten.

(Incidentally, I'm pretty sure I've seen that versioning scheme before in VMS...)

**Comment by trijezdci** [comment]
If the file is not in the translation dictionary then the tool simply won't translate the file name, which is the same situation as without translation. No harm done.

Let's say you have one or more files that the filesystem can't handle, for example because they are too long. So you copy your git repo to a PDP-11 simulation running RT-11 and what happens? The files in the repo all get shortened and your build system will crap out on them, so nothing can get built anyway.

However, if your build system and your compiler is aware of the translation facility, then you could make a utility that generates the translation dictionaries prior to copying the repo to an RT-11 filesystem at which point you can then build on your PDP-11 setup without problem.

You do not stand to lose anything with translation. You can only gain.

**Comment by trijezdci** [comment]
As for Modula-2, this is due to the language design.

C and other languages operate on the basis of file names.

```c
#include "filename.ext".
```

But Modula-2 operates on the basis of Modula-2 identifiers defined in the source.

In C "modules" do not have identifiers. In Modula-2 they do.

```Modula-2
DEFINITION MODULE Foobar;
```
So you import modules, not files.

Consequently, the Modula-2 compiler needs to know what file to open when it finds an import directive. Some early Modula-2 systems used internal file systems where you needed to import your files into the file system of the compiler first. Others simply used the first 8 chars of the module name to guess the filename, but that means it breaks the language when two modules have names that do not differ in the first 8 characters, also Modula-2 is case sensitive and some file systems are not.

This is not limited to definition modules only. The compiler determines dependencies for both definition and implementation modules from the import lists in both.

If you have an implementation file that imports Foobar, then the compiler will want to see a symbol file for that module and it will need to map the Foobar identifier to a filename to find the symbol file.

Anyway, your call, not mine. You can lead a horse to the water, you can't make him drink.

**Comment by trijezdci** [comment]
As for having scope.c and scope.C both in your source tree, this is precisely the problem that our filename translation scheme aims to solve because we have run into the very same problem with our Modula-2 compiler on Windows and MacOS where filesystems are (at least by default) case insensitive.

As for the origin of version suffixes. Using the semicolon as a version suffix is part of the ISO 9660 standard, which may well have been influenced by the VMS filesystem as the latter predates the former.

**Comment by davidgiven** [comment]
(You realise you've just called me a horse, right? You may not have intended it to be, but that was insulting.)

As I said, I've done this before, and it never works. There are always --- _always_ --- problems where the state of the files and the state of the translation table get out of sync. It's the classic no-single-source of truth problem, which is fundamentally intractable.

In the example given, once the file on disk gets renamed, there's now a stale entry in the translation table. I can guarantee you that the user will forget to update the translation table and the entry will stay around until some time later when a new file on disk gets created a name that matches the translation table, with the result that it'll be silently remapped and resulting in unexpected and hard-to-debug behaviour. I've seen this happen. Other problems: multiple translation entries pointing at the same file; translation entries pointing at missing files; picking up the wrong translation file for a directory, or an outdated one...

In addition, adding this translation layer to the compiler suite as a whole is infeasible because we don't have control of the entire stack. For example: we don't own a lot of the build tools (`make`, `ninja`, `sed`, `ed`, `awk`, `lua`...), so they're always going to see untranslated filenames. So such a system is going to be fundamentally inconsistent anyway.

(Now that you've jogged my memory, I remember that in January I actually _removed_ def-filename-shortening code from the Modula-2 compiler because it was causing problems: https://github.com/davidgiven/ack/commit/893471a42eb4d189cc0ba1dac1864d6f151bccd7)

_However_:

The idea has merit provided it gets drastically reduced in scope. From looking at the source, the ACK does not care at all about the filenames of `.mod` files. There is no lookup of implementations based on module name. It's entirely happy to compile any module in any source file, and equally happy to link any object files together (including non-Modula-2 ones). The only time it ever cares about the module-to-filename mapping is when looking up `.def` files, which happens in exactly one place inside the compiler.

So, we:

- define that the source of truth for module names is the contents of the files.
- write a tool that scans the source `.mod` files and generates an index file of which module lives where. (There's actually most of a tool which does this already; see `lang/m2/m2mm`.)
- runs this tool as part of the user build system; the index file then becomes an ephemeral build artifact, regenerated on each build and never checked in.
- allow the index file to be passed to `em_m2`, where it is used for looking up `.def` files _only_.

This should be all that's needed to allow user application modules to live in files which don't match the module name, which should solve the short-filesystem issue.

But that's solving a rather different problem from the one this bug is aimed for.

**Comment by davidgiven** [comment]
This is fixed now.
